#? DOCKER -> Containerização de código, para individualizá-los

services:
  nlw-agents-pg:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: agents
    ports:
      - "5432:5432" # Redireciona o port da maquina pro port do Docker
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
